tensorpack/dataflow/imgaug/_test.py
tensorpack/dataflow/imgaug/crop.py
tensorpack/dataflow/imgaug/geometry.py
tensorpack/dataflow/imgaug/imgproc.py
tensorpack/dataflow/imgaug/meta.py
tensorpack/dataflow/imgaug/noise.py
tensorpack/dataflow/imgaug/noname.py

Minor bugfix imgaug

---

tensorpack/dataflow/common.py

To verify the shapes of incoming data from the dataflow it is good
to actually output them for debugging reasons.

More verbose information about dataflow

---

docs/casestudies/colorize.md
docs/casestudies/index.rst
docs/index.rst
docs/user/glance.md

Just some help with the documentation. This text contains a guideline written by somebody (myself) who did not implement the library.
I feel, that understand enough of your code to write this text. And I am still somebody, who is aware of the first obstacles when working with TensorPack.
Nice job with your sphinx scripts!

A small writeup for starting with TensorPack

---

examples/CTC-TIMIT/train-timit.py
examples/Char-RNN/char-rnn.py

````
find -type f -name '*.py' -exec sed -i 's/tf.nn.rnn_cell/tf.contrib.rnn/g' {} \;
find -type f -name '*.py' -exec sed -i 's/tf.nn.rnn/tf.contrib.rnn.static_rnn/g' {} \;
````

Change rnn-cell to fix #103

---

tensorpack/dataflow/imgaug/imgproc.py

This might solve #129 in a more convenience way
````python
from tensorpack import *
ds = ImageFromFile(["original.jpg"], channel=3)
ds = AugmentImageComponent(ds, [imgaug.Grayscale(keep_dim=True)])
print next(ds.get_data())[0].shape # gives (H, W, 1)
````

Add grayscale mapping

---

examples/A3C-Gym/run-atari.py

I added import statement to use OpenCV in run-atari.py. Please review.

Add import statement for OpenCV

---

examples/A3C-Gym/train-atari.py

import cv2

---

tensorpack/callbacks/inference.py
tensorpack/models/model_desc.py
tensorpack/tfutils/summary.py
tensorpack/train/config.py
tensorpack/train/feedfree.py
tensorpack/train/multigpu.py
tensorpack/utils/utils.py

This logs warnings about deprecated functions and also shows the
filename as well as the line number.

Add helper function/decorator for deprecation warning

---

docs/tutorial/dataflow.md
docs/tutorial/efficient-dataflow.md
tensorpack/callbacks/base.py
tensorpack/callbacks/inference.py
tensorpack/callbacks/param.py
tensorpack/callbacks/summary.py
tensorpack/dataflow/format.py
tensorpack/dataflow/imgaug/crop.py
tensorpack/dataflow/imgaug/noise.py
tensorpack/dataflow/imgaug/paste.py
tensorpack/tfutils/distributions.py
tensorpack/tfutils/gradproc.py
tensorpack/tfutils/optimizer.py
tensorpack/tfutils/symbolic_functions.py

add probably add some new ones :wink:

remove some typos from the documentation

---

examples/DeepQNetwork/common.py

Use monitors in DQN and A3C

---

tensorpack/dataflow/imgaug/geometry.py

https://github.com/ppwwyyxx/tensorpack/issues/170

added shifts and stepped rotations

---

tensorpack/callbacks/saver.py

To copy the current stored tensorflow model requires to save *.index and *.data files, so I rewire the copy lines to save them all.

update MinSaver function in saver.py

---

tensorpack/dataflow/common.py

solution from issue 207

---

examples/boilerplate.py
tensorpack/dataflow/raw.py

Change FakeData to support different data types and ranges of values. Motivation is to enable ci-tests for the boilerplate template.

fix bug in boilerplate

---

tensorpack/dataflow/imgaug/imgproc.py
tensorpack/dataflow/imgaug/noname.py

add two simple image augmentations:
transpose can be used together with flips for fast 90 deg rotations
minmaxnormalize is a linear scaling to a predefined range

transpose_and_minmaxnormalize

---

tensorpack/dataflow/common.py

I found it always confusing, that most functions use `name` and
PrintData expected `label`. Not sure, why I thought it was a good idea to name it `label`.

Fixing the PrintData argument

---

tensorpack/dataflow/imgaug/geometry.py

https://github.com/ppwwyyxx/tensorpack/issues/306

allow non-default borderValue

---

tensorpack/dataflow/image.py
tensorpack/dataflow/imgaug/base.py
tensorpack/dataflow/imgaug/crop.py
tensorpack/dataflow/imgaug/geometry.py
tensorpack/dataflow/imgaug/meta.py
tensorpack/dataflow/imgaug/noname.py

I'll do the rest later. I have attached the test code (requires matplotlib and skimage). Let me know what you think. I'll add AugmentImageCoordinates shortly.
[test.zip](https://github.com/ppwwyyxx/tensorpack/files/1154688/test.zip)

add _augment_coords implementation for many ImageAugmentor subclasses

---

tensorpack/dataflow/imgaug/geometry.py

Hi, 
I would like to propose an affine image augmentor in `dataflow.imgaug.geometry`. [Here](https://gist.github.com/vfdev-5/f14490f0f8407f8f8b6b3035d159dd55) is an example of such transformations applied on one image. I will be glad to hear comments about this PR.

add Affine geometry transformation

---

tensorpack/callbacks/saver.py

When the models are huge, it's useful to use MinSaver and to store models in other directory than tensorboard logs.

MinSaver takes into account checkpoint_dir.

---

tensorpack/models/registry.py

For some reason, I  encounter this problem again and again. I see this assert 2 lines below, but the error msg can be a little bit more verbose.

More verbose warning

---

tensorpack/tfutils/scope_utils.py

consider the combination with SaverRestorer(..., prefix="...")

add @under_variable_scope to ease the structuring of models,

---

tensorpack/dataflow/parallel.py
tensorpack/tfutils/scope_utils.py

use tf.AUTO_REUSE, add reuse arg to under_variable_scope and fix

---

docs/tutorial/symbolic.md

The keras example link in the doc seems to be outdated.

Update symbolic.md , edit the link to keras example 

---

tensorpack/models/conv2d.py

Added dilation_rate to Conv2D since Tensorflow supports it easily. Requires TF 1.5 or greater.

Add dilation_rate to Conv2D

---

.travis.yml

Updated the Travis build file and cleaned up build script with global variables.

Update Travis Tensorflow to latest version

---

tensorpack/utils/gpu.py

Added native Tensorflow method to check number of GPUs.

Increase GPU counting robustness

---

tensorpack/utils/gpu.py
tensorpack/utils/nvml.py

write NVML wrapper inspired by py-nvml but written from scratch.

add NVML binding

---

tensorpack/tfutils/summary.py

I switched the scipy.misc code to rely on cv2 for creating image summaries. Any changes welcome. Should fix #592

Fix for #592. Goodbye Scipy

---

tensorpack/contrib/keras.py

Should #756. Instead of misusing try-finally the common code is just extracted in a method and then called before returning. This should not fail on unassigned variable.

Refactor KerasModelCaller to prevent using an unassigned variable.

---

tensorpack/input_source/input_source.py
tensorpack/input_source/input_source_base.py
tensorpack/models/pool.py
tensorpack/models/tflayer.py
tensorpack/predict/base.py
tensorpack/predict/concurrency.py
tensorpack/predict/dataset.py
tensorpack/tfutils/collection.py
tensorpack/tfutils/export.py
tensorpack/tfutils/symbolic_functions.py
tensorpack/train/config.py
tensorpack/utils/argtools.py
tensorpack/utils/logger.py

Looks like some typo fixes were left committed...

Fix some more typos.

---

tensorpack/tfutils/argscope.py

Improving the information when using `tf.layers` similar to the layers provided by tensorpack (like Conv2D, etc). I don't know if this is the perfect solution.
It produces outputs like
```
[0615 09:36:52 @argscope.py:90]                conv0:    [None, 28, 28, 1] ->   [None, 28, 28, 32]
[0615 09:36:52 @argscope.py:90]             <unkown>:   [None, 28, 28, 32] ->   [None, 14, 14, 32]
[0615 09:36:52 @argscope.py:90]                conv1:   [None, 14, 14, 32] ->   [None, 14, 14, 32]
[0615 09:36:52 @argscope.py:90]                conv2:   [None, 14, 14, 32] ->   [None, 14, 14, 32]
[0615 09:36:52 @argscope.py:90]             <unkown>:   [None, 14, 14, 32] ->     [None, 7, 7, 32]
[0615 09:36:52 @argscope.py:90]                conv3:     [None, 7, 7, 32] ->     [None, 7, 7, 32]
[0615 09:36:52 …
```

allow verbose shape information output for tf.layers

---

docs/conf.py
docs/tutorial/efficient-dataflow.md
examples/CTC-TIMIT/create-lmdb.py
examples/CTC-TIMIT/train-timit.py
examples/SuperResolution/data_sampler.py
examples/SuperResolution/enet-pat.py
tensorpack/dataflow/dftools.py
tensorpack/dataflow/format.py
tensorpack/dataflow/serialize.py

DataFlow Serializers

---

examples/CaffeModels/load-vgg16.py

rewrite VGG16 as well

---

.travis.yml
tensorpack/dataflow/serialize.py
tensorpack/utils/develop.py
tests/run-tests.sh
tests/test_serializer.py

Test new serialize interface and HDF5 support. Mainly the missing features from #797 .

Add unit test for Serializer

---

examples/GAN/Image2Image.py

make the pix2pix support multi gpu trainning

make the pix2pix support multi gpu trainning

---

examples/GAN/CycleGAN.py
examples/GAN/GAN.py
examples/GAN/Image2Image.py

I always struggle to remember the order of arguments in 
```python
if nr_tower == 1:
trainer = GANTrainer(data, Model())
else:
trainer = MultiGPUGANTrainer(nr_tower, data, Model())
```

simplify GAN usage

---

examples/FasterRCNN/train.py

fix dp extraction bug for visualize().

---

tensorpack/predict/multigpu.py

fix a bug cause: "Graph is finalized and cannot be modified" in b79a9d3b7e7f6036e20330acd542f39a665da151 like #449

fix a bug cause Graph is finalized and cannot be modified like #449

---

tensorpack/tfutils/argscope.py

> Unless you want to send a simple several lines of PR that can be easily merged, please note the following:
Yep :smile: I am done.
I just need this for my own layers which are scattered among different modules. Why fixing my coding style, if the library can handle this case :-)

enable_arg_scope for a given function

---

tensorpack/dataflow/dataset/caltech101.py

Sorry :(, I will be sure to test it next time before saying it's done.

fix: train_or_test to name

---

examples/FasterRCNN/train.py
tensorpack/callbacks/prof.py
tensorpack/dataflow/dataset/ilsvrc.py
tensorpack/utils/timer.py

resolve #1197 
@armandmcqueen does this suffice what you need?
You can make it run more frequent than 1 epoch by `PeriodicTrigger(ThroughputTracker(), every_k_steps=100)`.

ThroughputTracker

---

examples/FasterRCNN/predict.py

Hi, ppwwyyxx!
Recently, I usually use to tensorpack example of FasterRCNN. tensorpack is a breakthrough. I like it.
Anyway, Faster-RCNN is a popular object detection model. so, many people perhaps use this example.
Sometimes, who use this example want to extract graph. I did too.
Of course there are examples of extraction.
but, I wanted to make it easy for anyone to use. so, i create pull request and modified predict.py
Thank you!

Feat. extract graph

---

tensorpack/dataflow/imgaug/external.py

Thanks for your contribution!
Unless you want to send a simple several lines of PR that can be easily merged, please note the following:
* If you want to add a new feature, 
please open an issue first and indicate that you want to contribute.
There are features that we prefer to not add to tensorpack, e.g. symbolic models
(see details at https://tensorpack.readthedocs.io/tutorial/symbolic.html).
Therefore it's good to have a discussion first.
* If you want to add a new example, please note that:
1. We prefer to not have an example that is too similar to existing ones in terms of the tasks.
2. Examples have to be able to reproduce (preferrably in some mesurable metrics) published or well-known experiments and results.
* Please run `flake8 .` under the root of this repo to lint your code, …

a doc typo in IAAugmentor

---

examples/FasterRCNN/config.py
examples/FasterRCNN/data.py

As per the issue #1411 , to enable negative dataset training, I have made few changes.

Prevent filtering of empty images

---

tensorpack/tfutils/varmanip.py

Fix https://github.com/tensorpack/tensorpack/issues/1527
Thanks for your contribution!
Unless you want to send a simple several lines of PR that can be easily merged, please note the following:
* If you want to add a new feature,
please open an issue first and indicate that you want to contribute.
There are features that we prefer to not add to tensorpack, e.g. symbolic models
(see details at https://tensorpack.readthedocs.io/tutorial/symbolic.html).
Therefore it's good to have a discussion first.
* If you want to add a new example, please note that:
1. We prefer to not have an example that is too similar to existing ones in terms of the tasks.
2. Examples have to be able to reproduce (preferrably in some measurable metrics) published or well-known experiments and results.
* Please run …

Fix f-string
