examples/ResNet/load-resnet.py
Add "load-resnet" example that is able to load resnet-50, 101 and 152 from caffemodels.
The model is implemented based on the Tensorpack resnet model, however some modifications are added to match the orginal Caffe implentation in Kaiming's repo.
=> add load-resnet from caffemodel

tensorpack/dataflow/format.py
Reading Lmdb databases in random order requires to shuffle the keys.
Note, "_txn.cursor()" returns (k,v) pairs. Currently, the
implementations tries to query by a (k,v) pair instead of the key
only.
=> Lmdb Reader

tensorpack/models/model_desc.py, tensorpack/train/base.py
This handles non-gradient-descent updates like batch-norm from
tfSlim and regularization losses by fetching the op-collections.
=> add tfSlim to examples

.travis.yml, README.md, tests/install-tensorflow.sh, tests/test_examples.py
Use Travis-CI to run some tests under the latest release of TensorFlow and nightly releases in python 2.7 and 3.5.
This is a clean version of #93, which cannot be opened again because of rebasing to master.
features:
- TensorFlow version is environment variable
- run tests with the latest nightly build of the current version to check changes in API (these are allowed to fail)
- run arbitrary Python scripts with a timeout to test imports
for output see:
https://travis-ci.org/ppwwyyxx/tensorpack/builds/191097681
This further allows to:
- add tests for dataflow from this lib
- add python [unit-tests](https://docs.python.org/2/library/unittest.html)
- automatically [deploy Sphinx-doc](https://drdoctr.github.io/doctr/)
- automatically [deploy pip …
=> Add continous integration

examples/SimilarityLearning/mnist-embeddings.py, requirements.txt, tensorpack/callbacks/steps.py, tensorpack/tfutils/symbolic_functions.py
Sometimes it is necessary to inspect scalar values within an epoch.
This commit replaces tqdm with a modification to support livedata.
This should also be benchmarked a large-scale models. In simple MNIST examples I get no significant overhead.
=> Add Livedata

tensorpack/dataflow/imgaug/imgproc.py
The current master branch gives
````
[0209 15:59:02 @image.py:74] ERR Got 9 augmentation errors.
Traceback (most recent call last):
File "/home/patwie/git/tensorpack/tensorpack/dataflow/image.py", line 68, in func
ret = self.augs.augment(x)
File "/home/patwie/git/tensorpack/tensorpack/dataflow/imgaug/base.py", line 76, in augment
img, params = self._augment_return_params(img)
File "/home/patwie/git/tensorpack/tensorpack/dataflow/imgaug/base.py", line 105, in _augment_return_params
img, prm = a._augment_return_params(img)
File "/home/patwie/git/tensorpack/tensorpack/dataflow/imgaug/base.py", line 42, in _augment_return_params
return (self._augment(d, prms), prms)
File "/home/patwie/git/tensorpack/tensorpack/dataflow/imgaug/meta.py", line 113, in _augment
img = …
```
=> fix typo `asypte` and remove casting error

.travis.yml, tensorpack/models/common.py, tensorpack/models/conv2d.py, tensorpack/models/fc.py, tensorpack/models/nonlin.py
After writing `x = Conv2D(...)` one can now access the used variables
by `w = x.variables.W` and `b = x.variables.b` if they exists.
This is much better than writing something like:
```
w = x.name.replace('/output:0', "/W:0").replace('tower0/', '')
w = tf.get_default_graph().get_tensor_by_name(w)
```
which would also break the InferenceRunner.
Now, I also rely on this feature. And I think this the most straightforward way to access the variables. I did a grep over the *.py files in the TensorFlow repo and so far found no collision.
=> Augment Tensors from Layers (fix #228)

examples/boilerplate.py, examples/mnist-tfslim.py, examples/mnist-visualizations.py, tensorpack/tfutils/symbolic_functions.py
the mnist-convnet.py examples was overloaded. This commit splits the
file into the most minimal mnist-convnet and mnist-tfslim. Further
it adds an example about the visualization of filters which
illustrates the usage of `VariableHolder`.
In addition, this also adds a boilerplate template for projects,
which might facilitate the process of starting a new project.
=> Simplify simple examples

tensorpack/train/input_source.py
Bugfix for StagingArea. It appears as though Tensorflow is not adding it in the old contrib location. Should be backwards compatible.
=> Corrected tensorflow module path for StagingArea

tests/case_script.py
A binary representation `"\n" * 5 + "hh".encode('utf-8')` reproduces
the error from travis-ci.
=> Fix string decode issue for python3

tensorpack/tfutils/sessinit.py
When fine-tuning a model, one might want to skip some tensors from
restoring.
The following example will not load the learning rate from the
checkpoint file:
```python
def _get_optimizer(self):
lr = symbolic_functions.get_scalar_var('learning_rate', 5e-3, summary=True)
return tf.train.AdamOptimizer(lr)
if args.load:
config.session_init = SaverRestore(args.load, ignore=['learning_rate'])
```
=> Add ignore to SaverRestore

examples/SimilarityLearning/mnist-embeddings.py, tensorpack/utils/logger.py
I already had a previous pull-request about the same issue. This time summon the courage I try to convince you again about this feature. (see `mnist-embedding.py` for example). Sometimes, one uses the same training script (ResNet-18 vs. ResNet-50, mnist-embedding.py 'cosing' vs. mnist-embedding.py 'triplet'). But the runs all are tagged by the common scheme:
```
mynetwork0512-133348
mynetwork0515-094639
mynetwork0515-094924
mynetwork0515-095128
mynetwork0515-095232
mynetwork0515-095259
mynetwork0515-095339
mynetwork0515-095424
mynetwork0515-095619
mynetwork0515-095722
mynetwork0515-095751
mynetwork0515-100318
mynetwork0515-101107
mynetwork0515-101613
mynetwork0515-101841
mynetwork0515-102313
mynetwork0515-103231
```
while they are completely different. There are two other ways of solving …
=> Add name to logger.autodir for different runs and simplify

examples/PennTreebank/PTB-LSTM.py, scripts/checkpoint-prof.py
Around March they included a stricter checking of variable scope, which leads to incompatibility with previous RNN implementations.
https://github.com/tensorflow/tensorflow/issues/8191
According to the example below, we need to set the reuse argument.
https://github.com/tensorflow/models/blob/master/tutorials/rnn/ptb/ptb_word_lm.py
=> Fix PTB example according to upstream changes

tensorpack/predict/base.py
The `OfflinePredictor` in the buggy version builds graph by:
``` Python
with self.graph.as_default():
input = PlaceholderInput()
input.setup(config.model.get_inputs_desc())
with TowerContext('', is_training=False):
config.model.build_graph(input)
```
When `input` is passed into `build_graph`, it is converted to a list of tensors by:
``` Python
if len(args) == 1:
arg = args[0]
if isinstance(arg, InputSource):
inputs = arg.get_input_tensors()  # remove in the future?
if isinstance(arg, (list, tuple)):
inputs = arg
else:
inputs = [arg]
else:
inputs = args
```
However, the `inputs` returned by `get_input_tensors()` is just `[arg]`. It might because that the `InputSource` used a wrong version of the virtual method `_get_input_tensors()`.
I am using Python 3.6 by the way.
=> Fix Predictor Build Graph

examples/DeepQNetwork/atari.py
OpenCV2 does not always display the visualization properly. 
For imshow to properly update, cv2.waitKey should be called. Without this line, the cv2 window does not refresh on my system with OpenCV version 2.4.9.1 on Debian with Python 2.7.9. More info can be found on [StackOverflow](https://stackoverflow.com/questions/44854699/why-does-the-cv2-imshow-does-not-render-without-cv2-waitkey).
=> Atari Visualization Bugfix

tensorpack/dataflow/imgaug/imgproc.py
The Augmentor imgaug.Hue did not work for floating point images. I found that the hue range of cv2.cvtColor() is 0-360 for floating point images (and 0-180 for 8-bit images), see
https://docs.opencv.org/3.2.0/de/d25/imgproc_color_conversions.html#color_convert_rgb_hsv.
=> Fixes bug with floating point images in imgaug.Hue

examples/ResNet/README.md, examples/ResNet/cifar10-preact18-mixup.py
ResNet-18 with preactivation as by https://github.com/kuangliu/pytorch-cifar is using ResNet with preactivation block with 2 consecutive convolution layers in the block. Existing implementation was using 3 convolutional blocks.
Exponentially decaying WEIGHT_DECAY replaced with fixed reference value.
Architecture aligned with main repository approach: defined functions for bottleneck and regular PreActResNet blocks.
Support for multiple depths added.
=> ResNet-mixup example: align implementation with one, referenced by original paper.

docs/conf.py, examples/mnist-convnet.py, tensorpack/models/__init__.py, tensorpack/models/common.py, tensorpack/models/conv2d.py, tensorpack/models/fc.py, tensorpack/models/pool.py, tensorpack/models/registry.py, tensorpack/models/regularize.py, tensorpack/models/softmax.py, tensorpack/models/tflayer.py, tensorpack/models/utils.py
#627 
Both old and tf.layers argument naming should be supported now. Here are some python hacks that seems to work.
BatchNorm TBD.
=> Accept tf.layers compatible argument names

tensorpack/dataflow/imgaug/base.py
There is an AssertionError raised if run the following code:
```python
from tensorpack.dataflow.imgaug import AugmentorList, Flip
augs = AugmentorList([Flip(horiz=True, prob=0.5), Flip(vert=True, prob=0.5)])
repr(augs)
```
and 
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-3-8b50ed8bccdb> in <module>()
1 augs = AugmentorList([Flip(horiz=True, prob=0.5), Flip(vert=True, prob=0.5)])
----> 2 repr(augs)
/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/imgaug/base.py in __repr__(self)
92         for idx, f in enumerate(fields):
93             assert hasattr(self, f), \
---> 94                 "Attribute {} not found! The default __repr__ only works if …
```
=> Fix AssertionError with repr on AugmentorList

tensorpack/models/pool.py
Follow up to #635.
Fixes the following error loading resnet-50 weights, where gap layer output resulted in shape `[None, 7]` instead of `[None, 2048]`:
```
3rdparty/tensorpack/tensorpack/predict/base.py:170: in __init__
config.session_init._run_init(sess)
3rdparty/tensorpack/tensorpack/tfutils/sessinit.py:220: in _run_init
upd.update({name: value for name, value in six.iteritems(self._prms) if name in intersect})
3rdparty/tensorpack/tensorpack/tfutils/varmanip.py:111: in update
SessionUpdate.load_value_to_var(v, value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
var = <tf.Variable 'linear/W:0' shape=(7, 1000) dtype=float32_ref>
val = array([[ 0.03154677, -0.00305561,  0.10681453, ..., -0.0088307 ,
-0.01100363, -0.01323848],
[-0.0161896...6],
[ …
```
=> GlobalAveragePooling: convert to tf.layers data_format

examples/ResNet/cifar10-preact18-mixup.py
Was reading this code and thought about fixing what I think is a typo in a variable name. I know this is trivial, so feel free to ignore this pull request.
=> Fixing a typo in variable name

tensorpack/callbacks/monitor.py
When uploading the event files to an object storage like GCS, one cannot append to the file. Therefore, it's much cheaper & faster if multiple event files are created as only the last one is actually uploaded.
I believe it's functionality is equivalent to tf.train.Supervisor
Tested on example mnist.
=> Add option to write multiple tensorboard event files.

tensorpack/dataflow/parallel.py, tensorpack/dataflow/parallel_map.py, tensorpack/dataflow/remote.py
The `.bytes` explicitly triggers a copy in order to create a Python `bytes` object. This isn't necessary for pyarrow deserialization.
=> Removed excess copying when fetching data from ZMQ

tensorpack/dataflow/common.py
Doing:
```
ds = RepeatedData(ds, -1)
ds = PrefetchDataZMQ(ds, num_workers)
ds.reset_state()
```
Would blow up, since `RepeatedData` raises a ValueError, and `PrefetchDataZMQ` only checks for `NotImplementedError`.
Not the cleanest fix but 🤷‍♂️
=> Fix RepeatedData + PrefetchDataZMQ

tensorpack/predict/config.py
Some models do not need inputs during inference, e.g. GANs. However,
it was necessary to feed dummy-inputs although they are not needed.
=> Remove assert `len(self.input_names)` in `PredictConfig`

examples/basics/mnist-tflayers.py, tensorpack/tfutils/argscope.py
As `tf.layers` already contains most basic operation it would be nice to extend `argscope` from Tensorpack to support `tf.layers`.
This is **not** a ready-to-merge pull-request.
=> support tf.layers in argscope

examples/CaffeModels/load-vgg19.py
As part of the transition towards tf.layers #291, #627 this is a
rewrite. While The LinearWrap might need less lines, tf.layers are
supported by TensorFlow. And the motivation of tensorpack is being
a training framework.
=> Change VGG19 example to tf.layers.

.lgtm.yml
Add libcap-dev intallation in the LGTM build configuration
@ppwwyyxx this will make the LGTM build pass as discussed [here](https://github.com/ppwwyyxx/OpenPano/pull/73)
=> Add LGTM configuration file to fix build failure.

docs/tutorial/inference.md
To add missing tensorpack prefix part of import line for making snippet code more clear.
=> May be missing prefix in tutorial code?

examples/FasterRCNN/config.py, examples/FasterRCNN/data.py
The previous way to thresh anchor boxes based on iou is not a good metric.  For example, small anchors inside large crowd box would have small iou so not being ignored.
This PR update crowd label handling logic. Here, we use ioa instead of iou so that anchors that overlap with crowd boxes could be properly filtered out.
=> update crowd label handeling

tensorpack/tfutils/summary.py
OpenCV does not fully compress PNGs by default. This additional parameter tells OpenCV to use the maximum PNG compression level for encoding images. This should reduce the size of saved Tensorboard images particularly for highly compressible domains such as segmentations.
=> Improve PNG compression in add_image_summary

setup.py
Closes #1148.
When `tensorpack` was installed by wheel the platform was already evaluated
and thus `python-prctl` was installed, even though it is Linux-specific.
Installing from source package or sources was OK.
Instead use a platform specifier that is evaluated while installing the wheel.
=> Prevent install python-prctl outside Linux when installing by wheel

tensorpack/dataflow/dataset/__init__.py, tensorpack/dataflow/dataset/caltech101.py, tensorpack/libinfo.py
Hi,
I created a loader for Caltech101 dataset inspired by Mnist dataset. The data are downloaded from [https://people.cs.umass.edu/~marlin/data.shtml](https://people.cs.umass.edu/~marlin/data.shtml).
Because you used only train or test split, I merged train and validation set in train.
There are 2 problems. First, I used scipy.io.loadmat to load the file and it add scipy library as a dependancy if we want to use this dataset. Secondly, I did not check the file like you have done with the magic number for Mnist.
Feel free to comment and propose improvement, I will update this pull request accordingly.
=> feat: add Caltech101 Silouettes dataset

tensorpack/contrib/keras.py
If the keras learning phase is set to a constant (e.g. via `K.set_learning_phase(0)`) before a model function is called, the learning phase is not a tensor and hence has no consumers. Don't need to register the phase callback in this case.
=> Don't add Keras phase callback if learning phase is fixed

examples/keras/mnist-keras.py
Otherwise I see the following error:
```
InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'conv2d_input' with dtype float and shape [?,28,28,1]
[[node conv2d_input (defined at examples/keras/mnist-keras.py:45) ]]
```
This way keras does not create an unnecessary Input and determines the shape from [`image`](https://github.com/tensorpack/tensorpack/blob/master/examples/keras/mnist-keras.py#L69)
=> fix "mnist-keras.py"

docs/conf.py, docs/tutorial/extend/augmentor.md, examples/FasterRCNN/common.py, examples/FasterRCNN/data.py, examples/HED/hed.py, tensorpack/dataflow/image.py, tensorpack/dataflow/imgaug/_test.py, tensorpack/dataflow/imgaug/base.py, tensorpack/dataflow/imgaug/convert.py, tensorpack/dataflow/imgaug/crop.py, tensorpack/dataflow/imgaug/deform.py, tensorpack/dataflow/imgaug/external.py, tensorpack/dataflow/imgaug/geometry.py, tensorpack/dataflow/imgaug/imgproc.py, tensorpack/dataflow/imgaug/meta.py, tensorpack/dataflow/imgaug/misc.py, tensorpack/dataflow/imgaug/noise.py, tensorpack/dataflow/imgaug/paste.py, tensorpack/dataflow/imgaug/transform.py, tensorpack/utils/develop.py, tests/run-tests.sh
This deprecates the old interface of "Augmentor".
The `.augment` interface stays unchanged. The ones involving "parameters" (which I mainly learned from an ancient training system at Megvii) are changed.
Old interface:
```
im, params = aug.augment_return_params(im)
im2 = aug.augment_with_params(im2, params)
coords = aug.augment_coords(coords, params)
```
New interface:
```
tfm = aug.get_transform(im)  # a deterministic transform
im = tfm.apply_image(im)
im2 = tfm.apply_image(im2)
coords = tfm.apply_coords(coords)
```
Issues with the old one:
1. It returns an opaque object "params" and expect users pass it back. This is not a good design
2. Verbose and complicated interface
The new one replaces "params" by well-defined `Transform` instances, with their own methods to perform deterministic …
=> Make augmentors return a `Transform` instance.

tensorpack/train/trainers.py
Latest version of horovod ends with "post1", not an integer and broke trainers.py
=> fix trainers.py error with latest version of horovod (0.17.0.post1)

tensorpack/callbacks/monitor.py, tensorpack/callbacks/saver.py, tensorpack/utils/fs.py
Removed normalizing the path where the TensorFlow checkpoints, model and TensorBoard event files are saved in order to be able to save these to remote storages in the Cloud, like Google Cloud Storage, which are references with paths like gs://BUCKET_NAME/path/to/folder.
=> Save checkpoints and event files on Google Cloud Storage

tensorpack/models/conv2d.py, tensorpack/models/models_test.py
Tensporpack implementation for Transpose Convolution is used when TF-version > 1.12.
In this implementation, output shape is calculated without taking padding into consideration.
I added support for valid/full padded Transpose Convolution in this pull request (which is consistent with tf.layers implementation).
=> Transpose Convolution Valid/Full Padding

tensorpack/models/conv2d.py, tensorpack/models/models_test.py
Conv2DTranspose fails when either height or width shape is None since `tf.Dimension(None) is None ` doesn't evaluate to True. It seems that up until [#1323](https://github.com/tensorpack/tensorpack/pull/1323)  it was a silent bug, since arithmetic operations on tf.Dimension(None) are allowed
=> Transpose conv bug

tensorpack/dataflow/common.py, tensorpack/tfutils/gradproc.py, tensorpack/utils/logger.py
Fixed some deprecations warning on Python 3:
* importing `Mapping` directly from `collections` has been deprecated since python 3.3. It should be imported from `collections.abc` instead. [[source]](https://docs.python.org/3.8/library/collections.html)
* `inspect.getargspec` has been deprecated since python 3.0, and should be replaced with `inspect.getfullargspec` [[source]](https://docs.python.org/3/library/inspect.html#inspect.getargspec)
* `logging.warn` has been deprecated since python 3.3, and should be replaced with `logging.warning` [[source]](https://docs.python.org/3/library/logging.html#logging.warning). Actually, `logging.warn` has never been documented, even in python 2, and is only an alias for `logging.warning` that was kept for backwards compatibility …
=> Fixed some deprecation warnings on Python 3

examples/FasterRCNN/convert_d2/convert_d2.py
Convert Faster-RCNN with following command:
`python convert_d2.py --d2-config detectron2/configs/COCO-Detection/faster_rcnn_R_50_FPN_1x.yaml --d2-pkl model_final_b275ba.pkl --output R50FPN-d2-converted.npz`
Raise an error:
`  File "convert_d2.py", line 141, in <module>
tp_dict = convert_weights(d2_dict, cfg)
File "convert_d2.py", line 114, in convert_weights
_convert_conv(f"roi_heads.mask_head.mask_fcn{fcn+1}", f"maskrcnn/fcn{fcn}")
File "convert_d2.py", line 39, in _convert_conv
src_w = d.pop(src + ".weight").transpose(2, 3, 1, 0)
KeyError: 'roi_heads.mask_head.mask_fcn1.weight'`
This happens as the code tolerates mask_on. Add a flag to fix this.
=> Fix Faster-RCNN d2_convert error.

tensorpack/models/conv2d.py
By default, all tensorflow variable has the dtype `tf.float32`. So, if the input has dtype `tf.float16`, then in the branch I edited, there is a dtype miss-matching between the input and the variable.
It will cause the error
> TypeError: Input 'filter' of 'Conv2D' Op has type float32 that does not match type float16 of argument 'input'.
The bug is discovered by running the code under repo [https://github.com/facebookresearch/ImageNet-Adversarial-Training](ImageNet-Adversarial-Training) with the following command
```bash
python3 main.py --data [imagenet training data dir] \
--use-fp16xla --batch 256 --attack-iter 30 --attack-epsilon 16.0 --arch ResNeXtDenoiseAll -d 50
```
=> fix input dtype not matching variable dtype

tensorpack/input_source/input_source_base.py, tensorpack/train/config.py
When trying to run my tensorpack code (which I developed with tensorflow 1) with tensorflow 2.3, I got two errors inside tensorpack. I fixed both errors in these commits. Now my tensorpack code runs fine with tensorflow 2.3.
Best,
Philipp
PS: Thanks for developing tensorpack! It is a great library!
=> Improve compatibility to tensorflow 2.3

examples/FasterRCNN/eval.py, tensorpack/train/trainers.py
Added TensorFlow V1 compatibility fix to ```tensorpack/train/trainers.py``` and ```examples/FasterRCNN/eval.py``` so FasterRCNN model can be trained with latest version of TensorFlow 2.
=> TensorFlow Version 1 Compatibility Fix
